### ISSUE TITLE
[RFC] Link to Inspectio stickies

### ISSUE THREAD

**Issue by sandrokeil** [event-engine/cockpit#6]
It would be useful to add deep linking to the Inspectio stickies e.g. via annotation, event engine description or auto discovery.

There is one problem. How to handle multiple stickies with the same name? Maybe we can use the Inspectio search for this.

**Comment by codeliner** [comment]
One scenario I'm thinking about is the following:

1. Design a feature in InspectIO.
2. Generate boilerplate Event Engine code for that feature enhanced with PHP 8 attributes
3. Add metadata from PHP 8 attributes to Cockpit schema (like InspectIO boardId and elementId)

*Example event*
```
use InspectIO\Attributes\BoardId;
use InspectIO\Attributes\ElementId;

<<BoardId('26b07ebe-12e5-426f-8853-0ec7de128ede')>>
<<ElementId('89f76f99-f5cf-43bf-ac94-3c3d44c83dc7')>>
final class UserCheckedIn
{
  /* ... */
}
```
